  L.marker([-2574.75, 6485.5], {icon: cardIcon1}).addTo(map)
   .bindPopup("<h2>Insel 1</h3><p><a href='https://i.imgur.com/3sx9iLU.jpeg' data-lightbox='image-1' data-title='Insel 1'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'></div></div></p>");
  L.marker([-617, 3907.25], {icon: cardIcon1}).addTo(map)
    .bindPopup("<h2>Insel 2</h3><p><a href='http://epvpimg.com/ZbhMbab' data-lightbox='image-1' data-title='Insel 2'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-2574.75/6485.5'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div></p>");
  L.marker([-7242.5, 5172.25], {icon: cardIcon1}).addTo(map)
    .bindPopup("<h2>Insel 3</h3><p><a href='http://i.epvpimg.com/9bxweab.png' data-lightbox='image-1' data-title='Insel 3'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-2574.75/6485.5'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div></p>");
  L.marker([-5338.75, 5728.5], {icon: cardIcon1}).addTo(map)
    .bindPopup("<h2>Insel 4</h3><p><a href='https://i.imgur.com/ucu3rou.png' data-lightbox='image-1' data-title='Insel 4'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-2574.75/6485.5'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div></p>");
  L.marker([-3824.5, 6037.5], {icon: cardIcon1}).addTo(map)
    .bindPopup("<h2>Insel 5</h3><p><a href='https://i.gyazo.com/edff4206238a77d62cd394323e7f6040.png' data-lightbox='image-1' data-title='Insel 5'>Open In-Game Screenshot</a></p><div class='input-group input-group-sm mb-3'><input type='text' class='form-control' id='copy' value='https://rockstarnews.ru/map/#5/-2574.75/6485.5'><div class='input-group-append'><button class='btn btn-outline-secondary copy' data-clipboard-target='#copy' type='button'>Copy</button></div></div></p>");
